services:
  mongo:
    image: mongo:7.0
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    image: web_role_api
    build:
      context: ./backend
    ports:
      - "7878:7878"
    environment:
      MONGO_URI: mongodb://host.docker.internal:27017/webrole
    env_file:
    - backend/.env.docker
    depends_on:
      - mongo

  frontend:
    image: web_role_frontend
    build:
      context: ./frontend
    ports:
      - "5173:80"
    depends_on:
      - backend

# data storage
volumes:
  mongo_data:
